### PR TITLE
Add Peakon SCIM 2.0 implementation

### PR DESCRIPTION
**Pull request by sebreh**
Adds Peakon's SCIM 2.0 to the list of implementations.

More details here https://help.peakon.com/administering-your-account/technical-information-and-language-support/scim-api-integration-guide

### CODE REVIEW

**Comment by erdtman** [comment]
Looks good, but could you put it in alphabetic order.

**Comment by sebreh** [comment]
Of course, done :)

**Comment by sebreh** [comment]
@erdtman does this look ok to you now?

**Comment by erdtman** [comment]
Looks good

**Pull request merged**
